projectdir: /root/Voyage
server:
    ip_address: 0.0.0.0
    port: 80
twitter:
    initial_tweet_count: 3000
    iteration_tweet_count: 200
    from_start:  True
    min_iteration_time: 600
    wait_rate_seconds: 60
    consumer_key: UITySH5N4iGOE3l6C0YgmwHVd
    consumer_secret: H7lXeLBDQv3o7i4wISGJtukdAqC6X9Vr4EXTdaIAVVrN56Lwbh
    access_token: 2825329492-TKU4s0Mky7vazr60WKHQV7R6sJT2wYE4ysR3Gm3
article:
    min_iteration_time: 86400
storage:
    date_format: _%Y-%m-%dT%H:%M #leave _ at the start
    # "%Y-%m-%dT%H:%M"  - Universal date format for consistency
communication:
    comm_file: _comm.stream
    retry_count: 10
    retry_delta: 1
    sleep_time: 5
warc:
    dir: warc
    article_subdir: article
    twitter_subdir: twitter
pdf:
    dir: pdf
    article_subdir: article
    twitter_subdir: twitter

log:
    retention_days: 30
crawler:
    n: 5000
    k: 0.6
    postgresql:
      user: postgres
      password: password
      name: crawler
